name: Validate

on: 'push'

jobs:

  validation-build-ubuntu:
    name: Validate (Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup conan
      run: |
        pip3 install setuptools
        pip3 install conan
        ~/.local/bin/conan remote add conan-iceshard https://conan.iceshard.net/
        ~/.local/bin/conan profile new --detect default
        ~/.local/bin/conan profile update settings.compiler=clang default
        ~/.local/bin/conan profile update settings.compiler.version=9 default
        ~/.local/bin/conan profile update settings.compiler.libcxx=libstdc++11 default
    - name: Export
      run: |
        ~/.local/bin/conan create . lua/5.1.5@iceshard/stable
    - name: Success
      run: |
        echo 'Validation success'

  validation-build-windows:
    name: Validate (Windows)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup conan
      run: |
        pip3 install setuptools
        pip3 install conan
        conan remote add conan-iceshard https://conan.iceshard.net/
    - name: Export
      run: |
        conan create . lua/5.1.5@iceshard/stable
    - name: Success
      run: |
        echo 'Validation success'
